[tool.poetry]
name = "superset-test"
version = "0.1.0"
description = ""
authors = ["Nick Lis"]
readme = "README.md"
packages = [{include = "superset_test"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
